### ISSUE TITLE
Finetuning to each real dataset?

### ISSUE THREAD

**Issue by Rtakaha** [intelpro/CBMNet#2]
Hi, thank you very much for sharing your great work!

I have some questions regarding to [the paper](https://openaccess.thecvf.com/content/CVPR2023/papers/Kim_Event-Based_Video_Frame_Interpolation_With_Cross-Modal_Asymmetric_Bidirectional_Motion_Fields_CVPR_2023_paper.pdf).

To compare with TimeLens, you mention that TimeLens is fine-tuned on the trainset with the same number of epochs.
> For a fair comparison, we finetune the only public event-based VFI method [43] on our trainset with the same number of epochs as ours.

1. Does this mean CBMNet is also finetuned with the trainset of ERF-X170FPS Dataset? It seems it's not mentioned in the paper if the model is finetuned or not.
1. For the evaluations with other real dataset (Table 3), did you also finetune the models to each dataset?
1. Are the weights provided in this repo finetuned with ERF-X170FPS?

Thank you very much.

**Comment by intelpro** [comment]
1) Yes, 2) Yes 3) Yes

**Comment by Rtakaha** [comment]
Thank you!
