### ISSUE TITLE
Why multiply the coordinates by 128?

### ISSUE THREAD

**Issue by DachunKai** [intelpro/CBMNet#6]
Why do we need to multiply the x and y coordinates by 128 when saving data?

**Comment by hjyyyd** [comment]
> Why do we need to multiply the x and y coordinates by 128 when saving data?

因为事件坐标投影到图片之后，坐标会是浮点数。用浮点数保存，事件的npz文件会很大。所以事件的数据都会乘以一个数字后再用int型保存，保留了一定的精度，同时减小文件大小

**Comment by DachunKai** [comment]
> > Why do we need to multiply the x and y coordinates by 128 when saving data?
> 
> 因为事件坐标投影到图片之后，坐标会是浮点数。用浮点数保存，事件的npz文件会很大。所以事件的数据都会乘以一个数字后再用int型保存，保留了一定的精度，同时减小文件大小

谢谢！那实际使用这些坐标数值时，再除以128吗？除以128后，很大一部分的x, y不是整数了，怎么处理呢？

**Comment by DachunKai** [comment]
> > Why do we need to multiply the x and y coordinates by 128 when saving data?
> 
> 因为事件坐标投影到图片之后，坐标会是浮点数。用浮点数保存，事件的npz文件会很大。所以事件的数据都会乘以一个数字后再用int型保存，保留了一定的精度，同时减小文件大小

谢谢！明白了
